#!/usr/bin/env python3
"""Regenerate the fixed-command tools in jev/tools/ from the table below.

Each is one file, self-contained like every tool file here (upstream compiles a
tool alone, so the runner is repeated in each rather than shared). They differ
in four things only: the verb, the description, the one fixed command, and the
tools' own name. Edit the table, run this, commit the result.

    python3 tests/jev/gen_probes.py          write the files
    python3 tests/jev/gen_probes.py --check  exit 1 if a file differs from what would be written
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOOLS = os.path.join(HERE, "..", "..", "jev", "tools")

# stem, what it shows, the one command it runs
PROBES = [
    ("os_release", "The operating system's release file: name, version, id.", "cat /etc/os-release"),
    ("uname", "The kernel's name, release and the machine's architecture.", "uname -a"),
    ("hostname_uptime", "The host's name and how long it has been up, with load.", "hostname; uptime"),
    ("who", "Who is logged in, and from where.", "who"),
    ("listening", "The sockets the host is listening on, with the process that owns each.", "ss -tulpn 2>/dev/null || netstat -tulpn"),
    ("established", "The established TCP connections, with the process that owns each.", "ss -tnp state established"),
    ("addresses", "The network interfaces and their addresses, one line each.", "ip -br addr"),
    ("firewall", "The firewall's rules (nftables, or iptables if there is no nft).", "nft list ruleset 2>/dev/null || iptables -S"),
    ("processes", "The 30 busiest processes by CPU: command, pid, user, cpu, elapsed time.", "ps -eo comm,pid,user,pcpu,etime --sort=-pcpu | head -30"),
    ("juice_headers", "The HTTP response headers of the local OWASP Juice Shop lab at http://127.0.0.1:3001/ (a HEAD request).", "curl --max-time 10 -fsS -I http://127.0.0.1:3001/"),
    ("juice_robots", "robots.txt of the local OWASP Juice Shop lab at http://127.0.0.1:3001/.", "curl --max-time 10 -fsS http://127.0.0.1:3001/robots.txt"),
]

TEMPLATE = '''// `jev_%(stem)s`: runs one fixed command, `%(command)s`, and returns its output.
//
// The command is part of this file, not an argument: a graph that wants it calls
// this tool, and the gate sees a verb that can run exactly this and nothing else.
// By default it runs here. With `distro` it runs inside that WSL distribution
// (`wsl.exe -d <distro> -e bash -lc ...`); with `ssh` it runs on that host
// (`ssh -o BatchMode=yes ...`), for a target that is not this machine. Both are
// optional and neither is needed for the common case. They are checked to be
// plain names before they reach a command line.
//
// A command that does not succeed is an error: non-zero exit, timeout, no such
// program, or ssh itself failing. The error text is what the program printed with
// its `[exit code N]` line, so a graph's ERROR route and a reader both see why.
//
// This file is generated by tests/jev/gen_probes.py; the runner below is the same in
// every jev_* command tool, and a tool file is one file you can hand to somebody.

pub fn manifest() {
    #{
        name: "jev_%(stem)s",
        description: "%(desc)s Runs `%(command)s`, read-only, here or (with distro or ssh) elsewhere. Part of the jev recon graphs; takes no command from the caller.",
        approval: "read_only",
        input_schema: #{
            "type": "object",
            "properties": #{
                "distro": #{ "type": "string", "description": "Run inside this WSL distribution (wsl.exe -d <distro>). Optional; letters, digits, '.', '_', '-'." },
                "ssh": #{ "type": "string", "description": "Run on this host over ssh (user@host or host). Optional; key-based only (BatchMode)." },
                "ssh_port": #{ "type": "integer", "description": "The ssh port, with ssh. Default 22." },
            },
        },
    }
}

const COMMAND = "%(command_rn)s";

// A string field of the input, or "" when it is absent, null or not a string.
fn field(input, name) {
    match input.get(name) {
        Some(v) => if v is String { v.trim() } else { "" },
        None => "",
    }
}

fn plain(s, allow_at) {
    let first = true;
    for c in s.chars() {
        let ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')
            || c == '.' || c == '_' || c == '-' || (allow_at && c == '@');
        if !ok || (first && c == '-') {
            return false;
        }
        first = false;
    }
    !first
}

pub async fn call(input) {
    let distro = field(input, "distro");
    let ssh = field(input, "ssh");
    if distro != "" && ssh != "" {
        return Err("give distro or ssh, not both");
    }
    let program = "bash";
    let args = ["-c", COMMAND];
    if distro != "" {
        if !plain(distro, false) {
            return Err(`not a distro name: ${distro}`);
        }
        program = "wsl.exe";
        args = ["-d", distro, "-e", "bash", "-lc", COMMAND];
    }
    if ssh != "" {
        if !plain(ssh, true) {
            return Err(`not an ssh target: ${ssh} (user@host or host, plain characters only)`);
        }
        let port = "22";
        match input.get("ssh_port") {
            Some(p) => {
                if p is i64 || p is String {
                    port = `${p}`;
                }
            }
            None => {}
        }
        match port.parse::<i64>() {
            Ok(n) => {
                if n < 1 || n > 65535 {
                    return Err(`not an ssh port: ${port}`);
                }
            }
            Err(_) => return Err(`not an ssh port: ${port}`),
        }
        program = "ssh";
        args = ["-o", "BatchMode=yes", "-o", "ConnectTimeout=10", "-p", port, ssh, "--", COMMAND];
    }
    let out = eidolon::exec(program, args, Some(30)).await?;
    // wsl.exe's own messages (no such distribution, ...) are UTF-16; drop the NULs
    // so a reader sees text rather than a letter between NULs.
    let out = if distro != "" { out.replace("\0", "") } else { out };
    if out.starts_with("[exit code") || out.starts_with("[timed out") {
        if ssh != "" && out.starts_with("[exit code 255]") {
            return Err(`ssh to ${ssh} failed: ${out}`);
        }
        return Err(out);
    }
    Ok(out)
}
'''


def rn_string(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render(stem, desc, command):
    return TEMPLATE % {
        "stem": stem,
        "desc": rn_string(desc),
        "command": command,
        "command_rn": rn_string(command),
    }


def main():
    check = "--check" in sys.argv
    stale = False
    for stem, desc, command in PROBES:
        path = os.path.join(TOOLS, stem + ".rn")
        want = render(stem, desc, command)
        have = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if have == want:
            print("ok     " + stem)
        elif check:
            print("STALE  " + stem, file=sys.stderr)
            stale = True
        else:
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(want)
            print("wrote  " + stem)
    sys.exit(1 if stale else 0)


if __name__ == "__main__":
    main()
